spring:
  application:
    name: JournalApp
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal